require "hyprlandrc.config"
require "hyprlandrc.permissions"
require "hyprlandrc.monitors"
require "hyprlandrc.windowrules"
require "hyprlandrc.workspacerules"
require "hyprlandrc.smartgaps"
require "hyprlandrc.keybinds"
require "hyprlandrc.autostart"
