# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/ded2f5e5-87d3-430c-9617-efe31be4a5df";

  fileSystems."/home" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/root" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/nix/store" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@nix_store" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2871-5003";
      fsType = "vfat";
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

