vim.opt.encoding = "utf-8"
vim.opt.mouse = "a"
vim.opt.title = true
vim.opt.cursorline = true
vim.opt.errorbells = false
vim.opt.cmdheight = 2
vim.opt.timeoutlen = 1000
vim.opt.ttimeoutlen = 0
vim.opt.laststatus = 2
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.copyindent = true
vim.opt.smarttab = true
vim.opt.expandtab = false
vim.opt.tabstop = 4
vim.opt.softtabstop = 0
vim.opt.shiftwidth = 0
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.showmatch = true
vim.opt.smartcase = true
vim.opt.clipboard = "unnamedplus"
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undofile = true
vim.opt.foldmethod = "syntax"
vim.opt.foldlevelstart = 99 -- By default all folds are open
vim.opt.undodir = os.getenv "HOME" .. "/.local/share/nvim/undo"
vim.opt.colorcolumn = { "80", "120" }
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.termguicolors = true
vim.opt.updatetime = 1000
vim.opt.scrolloff = 15
vim.opt.virtualedit = "block"
vim.opt.inccommand = "split"

vim.opt.spelllang = "pt,en_gb"

vim.cmd "filetype plugin on"
