{ lib, pkgs, ... }:
let
  inherit (import ./util.nix { inherit lib; }) insertChunk;
in
{
  programs.neovim.plugins = [
    {
      type = "lua";
      config = insertChunk ./lua/plugin/treesitter.lua;
      plugin = (
        pkgs.vimPlugins.nvim-treesitter.withPlugins (
          p: with p; [
            angular
            arduino
            asm
            awk
            bash
            bibtex
            c
            clojure
            cmake
            comment
            commonlisp
            cpp
            c_sharp
            css
            csv
            dart
            desktop
            diff
            disassembly
            dockerfile
            doxygen
            editorconfig
            elixir
            elm
            erlang
            fennel
            forth
            fsharp
            gdscript
            gdshader
            gitattributes
            gitcommit
            git_config
            gitignore
            git_rebase
            glsl
            gnuplot
            go
            goctl
            godot_resource
            gomod
            gosum
            gotmpl
            gpg
            graphql
            groovy
            haskell
            hlsl
            html
            http
            hyprlang
            idris
            ini
            java
            javadoc
            javascript
            jq
            json
            json5
            julia
            kotlin
            latex
            llvm
            lua
            luadoc
            make
            markdown
            markdown_inline
            matlab
            meson
            nasm
            ninja
            nix
            objdump
            ocaml
            ocaml_interface
            ocamllex
            pascal
            passwd
            perl
            prolog
            python
            r
            racket
            regex
            rst
            rust
            scala
            scheme
            scss
            sql
            ssh_config
            strace
            toml
            typescript
            udev
            vim
            vimdoc
            xml
            yaml
            zig
            zsh
          ]
        )
      );
    }
  ];
}
