{ pkgs, ... }:
{
  programs.neovim.plugins = [
    {
      type = "lua";
      config = builtins.readFile ./lua/plugin/treesitter.lua;
      plugin = (
        pkgs.vimPlugins.nvim-treesitter.withPlugins (
          p: with p; [
            arduino
            awk
            bash
            bibtex
            c
            cmake
            comment
            commonlisp
            cpp
            c_sharp
            css
            csv
            diff
            dockerfile
            elixir
            fennel
            gdscript
            gdshader
            gitattributes
            gitcommit
            git_config
            gitignore
            git_rebase
            glsl
            go
            godot_resource
            gpg
            groovy
            haskell
            hlsl
            html
            http
            ini
            java
            javascript
            jq
            json
            json5
            julia
            kotlin
            latex
            llvm
            lua
            make
            markdown
            markdown_inline
            matlab
            meson
            nasm
            ninja
            nix
            objdump
            ocaml
            ocaml_interface
            ocamllex
            passwd
            perl
            python
            r
            racket
            regex
            rst
            rust
            scheme
            scss
            sql
            ssh_config
            toml
            typescript
            vim
            vimdoc
            xml
            yaml
          ]
        )
      );
    }
  ];
}
